site_name: {{cookiecutter.project_name}}
repo_url: https://github.com/{{cookiecutter.github_handle}}/{{cookiecutter.project_name}}
site_url: https://{{cookiecutter.github_handle}}.github.io/{{cookiecutter.project_name}}
site_description: {{cookiecutter.description}}
site_author: {{cookiecutter.author}}
edit_uri: edit/main/docs/
repo_name: {{cookiecutter.github_handle}}/{{cookiecutter.project_name}}
copyright: Maintained by <a href="https://{{cookiecutter.github_handle}}.com">{{cookiecutter.github_handle}}</a>.

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Installation: installation.md
  - Usage: usage.md
  - Code Examples: code-examples.md
  - Content Tabs: content-tabs.md
  - Diagram Examples: diagram-examples.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/{{cookiecutter.project_slug}}"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/{{cookiecutter.github_handle}}/{{cookiecutter.project_name}}
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/{{cookiecutter.project_name}}

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details